services:
  bq-emulator:
    image: ghcr.io/goccy/bigquery-emulator:latest
    platform: linux/amd64          # ← Apple Silicon は必須
    container_name: bq-emulator
    ports:
      - "9050:9050"
    command: bigquery-emulator --project=local-project
